spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: wx123
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  mvc: #配置静态页面
    view:
      prefix: /templates/
      suffix: .html
  web:
    resources:
      static-locations: classpath:/META-INF/resources/ , classpath:/static/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.bean
  configuration:
    map-underscore-to-camel-case: true
